accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from accounts.views import signup


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path("receipts/", include('receipts.urls')),
    path("accounts/", include('accounts.urls')),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.contrib import admin
from django.urls import path, include, reverse, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views
from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    AccountListView,
    AccountCreateView,
    CategoryListView,
    CategoryCreateView,
)


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="receipt_create"),
    path("accounts/", AccountListView.as_view(), name="account_list"),
    path(
        "accounts/create/", AccountCreateView.as_view(), name="account_create"
    ),
    path("categories/", CategoryListView.as_view(), name="category_list"),
    path(
        "categories/create/",
        CategoryCreateView.as_view(),
        name="category_create",
    ),
]

receipts/models.py
from tkinter import CASCADE
from django.db import models
from django.conf import settings

# Create your models here.


class Receipts(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(decimal_places=3, max_digits=10)
    tax = models.DecimalField(decimal_places=3, max_digits=10)
    date = models.DateField(null=True)

    purchaser = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
    )

    category = models.ForeignKey(
      "Categories",
      related_name="receipts",
      on_delete=models.CASCADE,
      null=True
    )

    account = models.ForeignKey(
      "Accounts",
      related_name="receipts",
      on_delete=models.CASCADE,
      null=True,
    )

    def __str__(self):
      return self.name


class Categories(models.Model):
    name = models.CharField(max_length=50)

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Accounts(models.Model):
    name = models.CharField(max_length=100)
    number = models.PositiveIntegerField()

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

# function signup(request)
#     if the request method is "POST", then
#         form = UserCreationForm(request.POST)
#         if the form is valid, then
#             username = the "username" value from the request.POST dictionary
#             password = the "password1" value from the request.POST dictionary
#             user = create a new user using username and password
#             save the user object
#             login the user with the request and user object
#             return a redirect to the "home" path
#     otherwise,
#         form = UserCreationForm(request.POST)
#     context = dictionary with key "form" and value form
#     return render with request, "registration/signup.html", and the context

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("id_username")
            password = request.POST.get("id_password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {"form": form}
    return render(request, "registration/signup.html", context)

receipts/views.py
from distutils.log import Log
from multiprocessing import context
from unicodedata import category
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from receipts.models import Accounts, Categories, Receipts

# Create your views here.


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipts
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipts.objects.filter(purchaser=self.request.user)
    
    
class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipts
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account", ]
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")


class AccountListView(LoginRequiredMixin, ListView):
    model = Accounts
    template_name = "accounts/list.html"
    
    def get_queryset(self):
        return Accounts.objects.filter(owner=self.request.user)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Accounts
    template_name = "accounts/create.html"
    fields = ["name", "number"]
    
    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("account_list")


class CategoryListView(LoginRequiredMixin, ListView):
    model = Categories
    template_name = "categories/list.html"

    def get_queryset(self):
        return Categories.objects.filter(owner=self.request.user)


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = Categories
    template_name = "categories/create.html"
    fields = ["name",]
    
    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("category_list")

receipts/templates/accounts/create.html
{% extends 'base.html' %}

{% block content %}
<main>
  <form method = "post">
    {% csrf_token %}
    {{ form.as_p }}
    <div>
      <button>AH COUNT IT!</button>
    </div>
  </form>
  </main>
{% endblock content %}

receipts/templates/accounts/list.html
{% extends 'base.html' %}

{% block content %}
<main>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Number</th>
        <th>Number of Receipts</th>
      </tr>
    </thead>
      {% for account in accounts_list %}
      <tr>
        <td> {{ account.name }} </td>
        <td> {{ account.number }} </td>
        <td> {{ account.receipts.all|length }} </td>
      </tr>
      {% endfor %}
  </table>
</main>
{% endblock content %}

receipts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Two-Shot</title>
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
  </head>

<body>
		<header>
		  <nav>
        <ul class = "navigation">
          {% if user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'home' %}" >Receipts</a></li>
            <li class="nav-item"><a href="{% url 'receipt_create' %}">Create Receipt</a></li>
            <li class="nav-item"><a href="{% url 'account_list' %}">Accounts</a></li>
            <li class="nav-item"><a href="{% url 'account_create' %}">Create Account</a></li>
            <li class="nav-item"><a href="{% url 'category_list' %}">Categories</a></li>
            <li class="nav-item"><a href="{% url 'category_create' %}">Create Category</a></li>
            <li class="nav-item"><a href="{% url 'logout' %}">LOGOUT</a></li>
          {% else %}
            <li><a href="{% url 'login' %}">LOGIN</a></li>
            <li><a href="{% url 'signup' %}">SIGN UP</a></li>
          {% endif %}
        </ul>
		  </nav>
		</header>
	{% block content %}
	{% endblock content %}
</body>
</html>

receipts/templates/categories/create.html
{% extends 'base.html' %}

{% block content %}
<main>
  <h1>Create Category</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
      <button>CATAGORIZE THAT!</button>
  </form>
  </main>
{% endblock content %}

receipts/templates/categories/list.html
{% extends 'base.html' %}

{% block content %}
<main>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Number of Receipts</th>
      </tr>
    </thead>
      {% for category in categories_list %}
      <tr>
        <td> {{ category.name }} </td>
        <td> {{ category.receipts.all|length }} </td>
      </tr>
      {% endfor %}
  </table>
</main>

{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}

{% block content %}
<main>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <div>
    <button>PAY FOR THIS!</button>
  </div>
</form>
</main>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}

{% block content %}
<main>
  <table>
    <thead>
      <tr>
        <th>Vendor</th>
        <th>Total</th>
        <th>Tax</th>
        <th>Date</th>
        <th>Category</th> 
        <th>Account</th>
      </tr>
    </thead>
      {% for receipt in receipts_list %}
      <tr>
        <td> {{ receipt.vendor }} </td>
        <td> {{ receipt.total }} </td>
        <td> {{ receipt.tax }} </td>
        <td> {{ receipt.date }} </td>
        <td> {{ receipt.category }} </td>
        <td> {{ receipt.account }} </td>
      </tr>
      {% endfor %}
  </table>
</main>

{% endblock content %}